game:
  map-size: 4                 # Maximum number of players
  map-name: EpiwarsDefaultMap # Your map name
  min-players: 2              # Minimum number of players required to start a game
  player-to-win: 1            # Number of players needed to win the game
  countdown: 10               # Time in the waiting zone (in seconds)
  auto-start: 60              # Time before automatic start (in seconds)

# Specific configurations for the 'EpiwarsDefaultMap' map
EpiwarsDefaultMap-spawn:
  starting:
    x: 0.0
    y: 84.0
    z: 0.0
  pos1:
    x: 14.0
    y: 66.0
    z: 0.0
  pos2:
    x: -14.0
    y: 66.0
    z: 0.0
  pos3:
    x: 0.0
    y: 66.0
    z: 14.0
  pos4:
    x: 0.0
    y: 66.0
    z: -14.0

# Configuration of items in the chests
lootItems:
  0:
    material: WOODEN_SWORD
    chance: 0.5
    minAmount: 1
    maxAmount: 1
  1:
    material: STONE_SWORD
    chance: 0.5
    minAmount: 1
    maxAmount: 1
  2:
    material: IRON_SWORD
    name: "&cFire Sword"
    enchantments:
      FIRE_ASPECT: 5
    chance: 0.15
    minAmount: 1
    maxAmount: 1
  3:
    material: BOW
    enchantments:
      POWER: 3
      INFINITY: 1
    chance: 0.1
    minAmount: 1
    maxAmount: 1
  4:
    material: GOLDEN_SWORD
    enchantments:
      SHARPNESS: 2
    chance: 0.1
    minAmount: 1
    maxAmount: 1
  5:
    material: DIAMOND_SWORD
    enchantments:
      SHARPNESS: 3
      LOOT_BONUS_MOBS: 1
    chance: 0.05
    minAmount: 1
    maxAmount: 1
  6:
    material: IRON_HELMET
    chance: 0.1
    minAmount: 1
    maxAmount: 1
  7:
    material: LEATHER_CHESTPLATE
    chance: 0.4
    minAmount: 1
    maxAmount: 1
  8:
    material: DIAMOND_CHESTPLATE
    name: "&bDiamond Chestplate"
    chance: 0.05
    minAmount: 1
    maxAmount: 1
  9:
    material: IRON_LEGGINGS
    chance: 0.07
    minAmount: 1
    maxAmount: 1
  10:
    material: IRON_BOOTS
    chance: 0.7
    minAmount: 1
    maxAmount: 1
  11:
    material: COBBLESTONE
    chance: 0.35
    minAmount: 10
    maxAmount: 25
  12:
    material: STONE
    chance: 0.35
    minAmount: 10
    maxAmount: 25
  13:
    material: OAK_PLANKS
    chance: 0.35
    minAmount: 10
    maxAmount: 25
  14:
    material: IRON_ORE
    chance: 0.4
    minAmount: 1
    maxAmount: 5
  15:
    material: DIAMOND_ORE
    chance: 0.2
    minAmount: 1
    maxAmount: 5
  16:
    material: DIAMOND_BLOCK
    chance: 0.01
    minAmount: 1
    maxAmount: 5
  17:
    material: NETHER_BRICK
    chance: 0.35
    minAmount: 10
    maxAmount: 25
  18:
    material: END_STONE
    chance: 0.35
    minAmount: 10
    maxAmount: 25
  19:
    material: COOKED_BEEF
    chance: 0.2
    minAmount: 1
    maxAmount: 5
  20:
    material: GOLDEN_CARROT
    name: "&6Golden Carrot"
    chance: 0.1
    minAmount: 1
    maxAmount: 3
  21:
    material: EXPERIENCE_BOTTLE
    name: "&aExperience Bottle"
    chance: 0.1
    minAmount: 1
    maxAmount: 5
  22:
    material: ENDER_PEARL
    name: "&5Ender Pearl"
    chance: 0.1
    minAmount: 1
    maxAmount: 3
  23:
    material: BLAZE_ROD
    name: "&6Blaze Rod"
    enchantments:
      KNOCKBACK: 10
    chance: 0.1
    minAmount: 1
    maxAmount: 1
  24:
    material: IRON_INGOT
    name: "&7Iron Ingot"
    chance: 0.1
    minAmount: 1
    maxAmount: 3
  25:
    material: DIAMOND
    name: "&bDiamond"
    chance: 0.1
    minAmount: 1
    maxAmount: 3
  26:
    material: SNOWBALL
    chance: 0.3
    minAmount: 5
    maxAmount: 10
  27:
    material: GOLDEN_APPLE
    name: "&eGolden Apple"
    chance: 0.15
    minAmount: 1
    maxAmount: 2
  # Add more items with theirs chances, quantities, and possible enchantments